source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/toy/devel/smarthouse-101/tools/google-cloud-sdk/path.zsh.inc' ]; then . '/home/toy/devel/smarthouse-101/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/toy/devel/smarthouse-101/tools/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/toy/devel/smarthouse-101/tools/google-cloud-sdk/completion.zsh.inc'; fi
